ARG IMAGE_BASE=gitlab-registry.cern.ch/c2mon/c2mon
FROM ${IMAGE_BASE}

ARG C2MON_SERVER_PROPERTIES=conf/c2mon-server.properties
ADD ${C2MON_SERVER_PROPERTIES} /c2mon-server/conf/c2mon-server.properties

